default_config = {
    # 'accumulate_grad_batches': 'None',
    'accumulate_grad_batches': 4,
    'activation': 'shifted_gelu',
    'activations_initialization': 'uniform_same',
    'auto_lr_find': False,
    # 'auto_lr_find': True,
    # 'auto_scale_batch_size': 'None',
    'auto_scale_batch_size': 'binsearch',
    'batch_size': 37,
    'bin_side_in_m': 0.05,
    'box_height_in_m': 4.4,
    'box_width_in_m': 4.4,
    # 'gradient_clip_val': None,
    'gradient_clip_val': 0.1,
    'code_kernel_scale': 0.25,
    'code_kernel_scale_gradient': False,
    'code_kernel_type': 'exponential_negative_squared_distance',
    # 'code_kernel_type': 'inner_product',
    'code_space_interaction': 'squared_difference',
    # 'code_space_interaction': 'product',
    # 'code_space_interaction': 'info_nce',
    'compare_across_batch_dim': True,
    'dt': 0.1,
    'dynamics_noise_postactivation_std': 0.,
    'dynamics_noise_postnormalization_std': 0.,
    'dynamics_noise_preactivation_std': 0.,
    # 'dynamics_noise_preactivation_std': 0.2,
    'dynamics_noise_type': 'multiplicative',
    'learning_rate': 3e-5,
    # 'learning_rate_scheduler': 'cosine_annealing_warm_restarts',
    'learning_rate_scheduler': 'reduce_lr_on_plateau',
    'loss_coding_subsampling': 'constant_number 6',
    # 'loss_coding_subsampling': 'uniform 0.1',
    # 'loss_coding_prefactor': 1.,
    'loss_coding_prefactor': 0,
    'loss_covariance_offdiag_prefactor': 0.,
    'loss_conformal_isometry_prefactor': 0.,
    'loss_entropy_prefactor': 0.,
    'loss_hinge_activations_prefactor': 1.,
    'loss_path_integrating_fn_str': 'mse',
    'loss_path_integrating_prefactor': 0.,
    # 'loss_separation_fn_str': 'unit_norm_over_time',
    # 'loss_separation_fn_str': 'cov_matrix_norm_squared',
    # 'loss_separation_fn_str': 'cov_matrix_off_diagonal_norm_squared',
    'loss_separation_fn_str': 'negative_mse',
    # 'loss_separation_fn_str': 'second_moment_matrix_norm_squared',
    'loss_separation_prefactor': 0.,
    'loss_equal_positives_and_negatives': False,
    'mask_type': None,
    'n_epochs': 11,
    'n_grad_steps_per_epoch': 13,
    'n_input_dim': 2,
    'n_hidden_units': 32,
    'normalize_activations': True,
    'optimizer': 'adamw',
    'precision': 32,
    # 'precision': 16,
    # 'pretrain_run_id': 'b1m75gmv',
    'pretrain_run_id': 'None',
    # 'recurrent_dropout': 0.,
    # 'rnn_alpha': 0.7,
    'rnn_alpha': 1.,
    'rnn_n_input_mlp_layers': 3,
    'rnn_n_recurrent_mlp_layers': 1,
    'rnn_type': 'multiplicative_rnn',
    # 'rnn_use_recurrent_bias': True,
    'rnn_use_recurrent_bias': False,
    'seed': 0,
    'space_kernel_scale': 0.1,
    'space_kernel_type': 'exponential_negative_squared_distance',
    # 'space_kernel_type': 'equal',
    # 'space_kernel_type': 'distance_cutoff',
    # 'space_kernel_type': 'squared_distance',
    'start_trajectories_train': 'origin',
    'start_trajectories_val': 'origin',
    'subtrajectory_len': 8,
    # 'trajectory_type': 'brownian_bridge',
    # 'trajectory_type': 'discrete',
    # 'trajectory_type': 'circles',
    # 'trajectory_type': 'petals',
    # 'trajectory_type': 'permutations_discrete',
    # 'trajectory_type': 'concatenated_permutations_discrete',
    # 'trajectory_type': 'concatenated_permutations_uniform',
    'trajectory_type': 'uniform|permutations',
    'traj_len_randomize': False,
    'traj_len_curriculum': 'None',
    # 'traj_len_curriculum': 'Linear ( 1 , 1 )',
    'traj_len_train': 31,
    'traj_len_val': 23,
    'velocity_noise_std': 0.,
    # 'velocity_noise_std': 0.2,
    # 'weight_decay': 1e-6,
    'weight_decay': 0.0,
}
