default_config = {
    "accumulate_grad_batches": 1,
    "batch_size_train": 17,
    "batch_size_val": 13,
    "bin_side_in_m": 0.05,
    "box_height_in_m": 2.2,
    "box_width_in_m": 2.2,
    "check_val_every_n_epoch": 50,
    # "data_generation": "sampled_at_beginning",
    "data_generation": "sampled_at_every_step",
    "dt": 0.02,
    "gradient_clip_val": 1e-5,
    "head_direction_cell_concentration": 20.0,
    "hidden_state_init": "pc_hd",
    # "hidden_state_init": "pos_hd",
    "input_var": "egocentric",
    # "input_var": "allocentric",
    "keep_prob": 0.5,
    "learning_rate": 0.01,
    "learning_rate_scheduler": "None",
    "n_epochs": 11,
    "n_batches_per_epoch": 100,
    "n_head_direction_cells": 12,
    "n_hidden_units": 32,
    # "n_readout_layers": 1,
    "n_readout_layers": 2,
    "n_readout_units": 64,
    "n_place_cells": 72,
    "optimizer": "adam",
    "place_cell_rf": 0.05,
    "precision": 32,
    "rnn_type": "lstm",
    "seed": 0,
    "sequence_length_train": 31,
    "sequence_length_val": 37,
    "shuffle_train": True,
    # "target_var": "pc_hd",
    "target_var": "pos",
    "use_bias": False,
    "weight_decay": 1e-5,
}
