default_config = {
    'accumulate_grad_batches': 'None',
    'auto_lr_find': False,
    # 'auto_lr_find': True,
    'auto_scale_batch_size': 'None',
    'batch_size_train': 17,
    'batch_size_val': 13,
    'bin_side_in_m': 0.05,
    'box_height_in_m': 2.2,
    'box_width_in_m': 2.2,
    'data_generation': 'sampled_at_beginning',
    # 'data_generation': 'sampled_each_batch',
    'dt': 0.02,
    'gradient_clip_val': 1e-5,
    'head_direction_cell_concentration': 20.,
    'hidden_state_init': 'pc_hd',
    # 'hidden_state_init': 'pos_hd',
    'keep_prob': 0.5,
    'learning_rate': 0.01,
    'learning_rate_scheduler': 'None',
    'n_epochs': 11,
    'n_batches_per_epoch': 100,
    'n_head_direction_cells': 12,
    'n_hidden_units': 32,
    'n_readout_units': 64,
    'n_place_cells': 72,
    'optimizer': 'adam',
    'place_cell_rf': 0.05,
    'precision': 32,
    'rnn_type': 'lstm',
    'seed': 0,
    'sequence_length': 31,
    'use_bias': False,
    'weight_decay': 1e-5,
    # 'weight_decay': 0.0,
}
